create table if not exists gameinformations (
	gameinformations_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
	gameinformations_platformShortName varchar(255),
	gameinformations_gameCode varchar(255),
	gameinformations_name varchar(255),
	gameinformations_synopsis longvarchar
)